name: Hexo博客自动化部署
on:
  push:
    branches:
      - source  # 当 master 分支有 push 行为时触发这个 action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Git	# 安装Git
        run: sudo apt update && sudo apt install -y git
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # 指定 Node.js 版本

      - name: Install Dependencies # 安装项目依赖
        run: npm install  

      - name: Install hexo-cli   # 全局安装hexo-cli 
        run: |
          npm install -g hexo-cli 

      - name: Build Hexo # 生成 Hexo 页面
        run: |
          hexo clean
          hexo generate  

      - name: Generate static pages		# 生成博客
        run: hexo generate
        working-directory: ./public

      - name: Deploy to GitHub Pages	# 将生成的博客推送到你对应的仓库中
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HEXO_DEPLOY }}		# PERSONAL_TOKEN更换为你自己的token的名称，一定全写成大写
          publish_dir: ./public
          external_repository: Hosiang1026/Hosiang1026.github.io # 更改为你的 GitHub Pages 仓库，格式是username/repo
          publish_branch: master 



